version: '3.8'

services:
  bot:
    build: .
    container_name: visa-notification-bot
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/visa_bot
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    container_name: visa-bot-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=visa_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 